### ISSUE TITLE
Use svg icons

### ISSUE THREAD

**Issue by monich** [Wunderfitz/harbour-fernschreiber#102]
Fixed-sized png icons should be replaced with their svg equivalents to keep the UI resolution independent (those pngs are most likely generated from svgs anyway). Even if pngs get resized to a reasonable size on the screen, they won't look as great as properly rendered svgs when screen resolution doesn't match the expected one.

**Comment by jgibbon** [comment]
Mostly agreed, SVG is the simplest solution. It is a bit resource heavier to display than a bunch of pre-rendered pngs, though. 
That said, I always go the svg route if possible in my projects.

**Comment by monich** [comment]
It is heavier, which is why platform icons are pre-rendered for the target pixel density at the build stage but apps don't have a luxury of knowing that in advance. Another trick that may come in useful is colorization of icons with shaders like [this](https://github.com/monich/harbour-lib/blob/master/qml/HarbourHighlightIcon.qml). I'm not an expert in shaders by any means but that one works all the way back to Sailfish OS 2.0.

**Comment by jgibbon** [comment]
@Wunderfitz what is your stance on svg? I'd agree with @monich and say it's worthwhile.

For integrating in qml, we'd have to be careful to set the imageWidth/imageHeight (even if it equals width/height), otherwise it could potentially become blocky/blurry.

**Comment by Wunderfitz** [comment]
Sorry, don't have that much time and it will probably also be limited this weekend - my laptop either needs a fresh OS installation or I need a new laptop... :/

I actually don't care that much. If you think it's worth the effort with the respective adjustments and if we don't get a huge performance penalty, why not? Please find the zipped SVG icon attached (designed by the fabulous @iamnomeutente) which is the foundation for all Fernschreiber logos, icons and backgrounds in the app. If you want to change the visuals, please go ahead! :)

[harbour-fernschreiber-new.zip](https://github.com/Wunderfitz/harbour-fernschreiber/files/5431174/harbour-fernschreiber-new.zip)

**Comment by monich** [comment]
svgs are being rasterized according to their [sourceSize](https://doc.qt.io/qt-5/qml-qtquick-image.html#sourceSize-prop), for icons (and in most other cases too) that better be equal to the actual image size in pixels.

**Comment by jgibbon** [comment]
@monich Yeah, sorry, I meant sourceSize but wasn't able to confirm. Thanks for correcting me, I've updated my previous comment.

**Comment by GNUuser** [comment]
Woow. you fast & professional. Thank you  @jgibbon

**Comment by jgibbon** [comment]
@GNUuser I just finished up some things in my lunch break that were (mostly) done yesterday already. ;) But thanks.
