### ISSUE TITLE
Text Entities don't always line up

### ISSUE THREAD

**Issue by jgibbon** [Wunderfitz/harbour-fernschreiber#122]
For example the "New sign in"-Messages from Telegram contain Links or Bold text. 
These don't always line up with where they should be. 
I've noticed that it mostly happens where Umlauts are present in the entity text but haven't really investigated yet. 
First guess would be that it, for example, counts `&auml;` as 5 characters instead of one.

**Comment by Wunderfitz** [comment]
Should be fixed with f91079ca430711e3dbe641d7feeec0f0e562e5df please retest/have a look! :)

**Comment by jgibbon** [comment]
Looks good in the few messages I have that include those entities. Nice!
