### ISSUE TITLE
Don't load latest chat messages initially

### ISSUE THREAD

**Issue by jgibbon** [Wunderfitz/harbour-fernschreiber#136]
In high volume chats, the amount of unread messages will almost always be more than what is initially loaded, which means that you'll practically never get to the first unread message.

This behaviour may be the last bug preventing me from actually using Fernschreiber as my go-to default client.

**Comment by Wunderfitz** [comment]
Please retest and feel free to reopen in case it doesn't work... I'm not 100% sure, if it covers everything or if it even works in most cases... ;)

**Comment by jgibbon** [comment]
Does work generally, but it cuts the newer unread messages after a while. 

My first guess is that new messages received while not all previous messages are displayed just get appended instead of ignored. This would prevent the ones in between to get loaded.

**Comment by jgibbon** [comment]
Some more issues, possibly related to each other, to this and/or 18e88a84122281c921b6dc92f6252149004f9c48:
- Chats with few messages seem to not display all messages. In my example, the (private) chat contains 3 messages, 1 is shown.
- When forwarding some messages to chat with only few messages (same chat as above), the app crashes. I have previously encountered this only when forwarding directly to any chat while the page was "loading", which was fixed by using the Timer to start forwarding. Messages do get forwarded, the crash seems to happen while receiving them (see #1). Forwarding to a group with more messages still worked in my tests.

**Comment by Wunderfitz** [comment]
Fixes/improvements are now in branch https://github.com/Wunderfitz/harbour-fernschreiber/tree/chat-messages-136

**Comment by jgibbon** [comment]
Wow, I couldn't reproduce any of the mentioned bugs anymore. Good work!
Now I think I messed up testing the first issue last time I checked – if that's the case, please accept my apologies!

As the fix is already in master, as well, I'll just close this issue.
Thank you!
