### ISSUE TITLE
Remove send new message button when "Send message by enter" is chosen

### ISSUE THREAD

**Issue by iamnomeutente** [Wunderfitz/harbour-fernschreiber#143]
One could maybe remove the send new message button icon when "Send message by enter" is selected and move the attachment icon right.

**Comment by Wunderfitz** [comment]
Implemented by @santhoshmanikandan - closing this one. :)

**Comment by Wunderfitz** [comment]
Good point by @jgibbon in #252, never thought about it as I don't use this option. So reopening this one. What about showing the bubbles if an attachment is added? Would probably only be a small change...
