### ISSUE TITLE
"Mute chat" not working?

### ISSUE THREAD

**Issue by andywuest** [Wunderfitz/harbour-fernschreiber#144]
Hi, 

either mute chat is not working or i just do not understand it. If i mute a chat i would expect to get no more notifications when there is a new message (relevant for high traffic chats) - however this seems not to work. Also i would expect to be able to "unmute" the chat again. So after selecting the pully "mute chat" i would expect that the pully changes to "unmute chat" for this chat. Or do i understand something wrong here?

**Comment by andywuest** [comment]
Where / how can i see that a chat is muted?

**Comment by Wunderfitz** [comment]
Indeed it should work that way. A chat is muted if the crossed loudspeaker symbol is visible. Just tested with several chats - for me it still seems to work. Is that chat public in order to be able to reproduce it? Does it work with another client? 

![image](https://user-images.githubusercontent.com/15228698/98857019-bfe65080-245e-11eb-99f0-a147b49a0d15.png)

**Comment by iamnomeutente** [comment]
Maybe related, with Jolla Phone there is never notification independent from notification feedback settings.
Only one time I received a notification.
Does somebody of you still use the old Jolla Phone?

**Comment by andywuest** [comment]
Never seen that icon from the screenshots above - no matter if i mute the chat from the overview via the context menu or from within the chat via the pully. Afftects all kind of chats for me (Sailfish OS Community, as well as private ones with my contacts) .

However in the log file (when i start fernschreiber via the cli) - i get the following messages:

[TDLibWrapper] Notification settings for chat "243234" ....
[TDLibWrapper] Sending request to TD Lib, object type name: "setChatNotificationSettings"
[TDLibReceiver] Unhandled object type "ok"

Maybe the last message provides the hint why it is not working. Is the TDLIb bundled with fernschreiber. I have also depecher installed, i hope the TDLib version do not conflict with one another.

**Comment by jgibbon** [comment]
@andywuest Yes, TDLib is bundled, so that shouldn't be the issue. 

This reminds me: The "muted icon" is embedded in the text, so it may not be visible with long chat names or low resolutions. But that sounds like a completely different issue (which is why I've just created #156)

**Comment by andywuest** [comment]
Well, the length of the chat name / resolution is not the problem, because everything is visible (using a Sony XA 2 Plus which has a quite large screen). Switching to landscape mode does not change anything - and there the amount of space should be sufficient, by far.

**Comment by Wunderfitz** [comment]
I could reproduce it - muting wasn't working for chats that have never been muted before. A small attribute was missing to achieve that as well - will be fixed in the next version.
