### ISSUE TITLE
Prevent keyboard disappearing after sending a message

### ISSUE THREAD

**Issue by iamnomeutente** [Wunderfitz/harbour-fernschreiber#149]
Perhaps it would be better if the keyboard wouldn't disappear when a message is sent.
Especially if "send with enter" is selected it is quite uncomfortable like this in my opinion 
I think after clicking on the field to write a message it should never disappear until you click elsewhere on the screen independent from "send with enter" or not.

**Comment by Wunderfitz** [comment]
Mhmm, I prefer to hide - independently from the way the message is sent. But that can be made configurable... ;)

**Comment by iamnomeutente** [comment]
But what if you want to send more messages directly after an other? Or I send a message, I receive a message and then I want write an other message... I have to tap each time before writing.
But Sebastian, that's only my point of view, you don't have to change anything if you don't want to ;)

**Comment by Wunderfitz** [comment]
A small misunderstanding. Of course, I want to change it, but I would like to leave people the option to choose which variant they want to use. That's a very good feature request, it's open and will remain open until it's implemented. :)

**Comment by iamnomeutente** [comment]
Thank you guys ;)
