### ISSUE TITLE
Access Chat information page with a swipe

### ISSUE THREAD

**Issue by iamnomeutente** [Wunderfitz/harbour-fernschreiber#150]
Instead to access the chat information page only by clicking on the header it would be nice also with a swipe from right to left

**Comment by jgibbon** [comment]
Good idea, we thought about implementing it like that, but settled for the "click on header" approach first.

Just a reminder for when we come around to it: 
Usually, an "attached page" will directly be fully initialized, so we'll have to do some more optimizations on the information page first to not slow down loading the chat page itself too much.
