### ISSUE TITLE
Fernschreiber crashes if draft chat gets opend

### ISSUE THREAD

**Issue by Bsoupe** [Wunderfitz/harbour-fernschreiber#16]
If you try to open a draft started in another client or device, Frernschreiber crashes!

**Comment by Wunderfitz** [comment]
Not reproducible here, tried it with a private chat, a normal group and a supergroup. Did you do anything special, any more detailed steps for me?

**Comment by Bsoupe** [comment]
I can't reproduce it  (tried with a chat started on Teleports and a group chat). Coming from Telegram on an iPhone SE it doesn't crash too. Maybe it's fixed with on of the latest versions. Thank you!

**Comment by Bsoupe** [comment]
Solved
