### ISSUE TITLE
Group members list is repeated several times for some groups

### ISSUE THREAD

**Issue by jorm1s** [Wunderfitz/harbour-fernschreiber#166]
The group member list in the chat info page (opened by taping the top bar in any group chat) seems to be repeated several times for some groups, eg. the Fernschreiber Development group. I checked several groups and most of them had this bug, but didn't find any clear indicators which groups would or would not trigger this.

**Comment by jgibbon** [comment]
Thank you! I can reproduce this and will have a look in the next few days, since I am already changing a few things there.
