### ISSUE TITLE
Plurals in translations

### ISSUE THREAD

**Issue by mentaljam** [Wunderfitz/harbour-fernschreiber#20]
Hi,

Could you, please, use special formatting for plurals? For example

```diff
- %1 members
+ %n members
```

In some languages (for example, in Russian) there are several forms of plural. Formatting with `%1` looks really ugly.

UPD1: Also this string should be in plural `unread messages`. Something like

```qml
qsTr("unread message(s)", "0", count)
```

**Comment by jgibbon** [comment]
I'll have a look at this soon-ish.

Also, the pretty weird %n1 is present at some places – which may actually my fault. ;)

**Comment by monich** [comment]
> 
> In some languages (for example, in Russian) there are several forms of plural. Formatting with `%1` looks really ugly.
> 

Hmm, could you give an example when `%1` doesn't work but `%n` does? I've never had a problem with just `%1`.

**Comment by jgibbon** [comment]
I'll probably default to `%Ln` + third `qsTr()` argument + `.arg()` while adressing this to include localization of numbers.
