### ISSUE TITLE
Fix remorse popups

### ISSUE THREAD

**Issue by jgibbon** [Wunderfitz/harbour-fernschreiber#206]
- remove the wrapper
- make sure an actual page is set as a parent

This error is present on `ChatPage.qml` and `ChatInformationPageContent.qml`

**Comment by Wunderfitz** [comment]
Closing as it was obviously fixed with https://github.com/Wunderfitz/harbour-fernschreiber/commit/782599f90588336aac79976d744d2a699e884056
