### ISSUE TITLE
Too many items in the message context menu

### ISSUE THREAD

**Issue by monich** [Wunderfitz/harbour-fernschreiber#216]
All 6 items (Reply, Edit, Copy, Select, Pin, Delete) don't fit into the screen in landscape on most devices. Even 5 is one too many, I would say - the menu fills the entire chat area but at least it doesn't get clipped. Sixth item does get clipped.

**Comment by monich** [comment]
![Screenshot_20201201_001](https://user-images.githubusercontent.com/5909522/100731735-755c5200-33d4-11eb-97b7-48536f2f200f.png)

**Comment by monich** [comment]
As a side note, the word Message appearing in **EVERY** single menu item is a visual garbage, IMO. It's pretty obvious that items in the message context menu refer to the message, isn't it?

**Comment by GNUuser** [comment]
Too much message, If we use icons instead of message, will be optimized 90%, like all the options in one message bar.
Other option is separate the half, like 50% of message to icons to slide right left context.

**Comment by Wunderfitz** [comment]
Yep, that definitely needs to be improved. I'm wondering if there is a nice recommendation by Jolla how to solve such issues best. The [pitfalls page](https://sailfishos.org/develop/docs/silica/sailfish-application-pitfalls.html/) only say how NOT to do it, but doesn't provide nice solution examples.

**Comment by kraemera** [comment]
Just as an idea for a solution from a users perspective, have a look on how the menu on a podcast episode in habour-gpodder is done.

**Comment by monich** [comment]
> Just as an idea for a solution from a users perspective, have a look on how the menu on a podcast episode in habour-gpodder is done.

You mean icons?

**Comment by kraemera** [comment]
> > Just as an idea for a solution from a users perspective, have a look on how the menu on a podcast episode in habour-gpodder is done.
> 
> You mean icons?

Yes, I mean this:
![image](https://user-images.githubusercontent.com/20418590/101049943-4553b100-3584-11eb-9eae-bfd00c914792.png)

**Comment by monich** [comment]
Poll's context menu has 8 items, ouch...
