### ISSUE TITLE
Add an option to remove bubbles

### ISSUE THREAD

**Issue by ferlanero** [Wunderfitz/harbour-fernschreiber#223]
Please add an option to remove message bubbles in the same way it already exists with stickers. Bubbles overcharge viewing and adds an unnecessary complexity to chats view, as messages are enough differentiated with colors and aligning.

**Comment by Wunderfitz** [comment]
Shouldn't be a big deal. Let's see when we can include that! :)

**Comment by Wunderfitz** [comment]
Cleaning up a but, just saw that this feature request is already part of #23. Please follow-up there. Thanks!
