### ISSUE TITLE
No sounds in notifications

### ISSUE THREAD

**Issue by elvarr** [Wunderfitz/harbour-fernschreiber#233]
In version 0.5.1-2, there are no sounds in notifications.

**Comment by 24mu13** [comment]
same here
version: 0.6.1
Xperia X OS 3.4.0.24
I see visual notification but no sounds

**Comment by Wunderfitz** [comment]
Just FYI, this was a drawback for achieving Jolla Harbour compatibility (to get into the Jolla Store). [Nemo Notifications](https://sailfishos.org/develop/docs/nemo-qml-plugin-notifications/) is obviously not yet able to send out sound notifications. Thus, as long as nobody provides a convenient way of building two binaries (one for Jolla Store, one for OpenRepos) or as long as Jolla doesn't update this API, this issue will most certainly remain unchanged... :(

**Comment by monich** [comment]
I'm reasonably sure that sounds are possible, it's one of the things that I might want to check out at some point...

**Comment by broncheolus** [comment]
Would be really great if you could work this out, because for many people the possibility of sound notifications is a central point in messengers. Thanks for all your efforts. Keep on going. Greetings from Austria.
PS: Every day I check for next releases of FS because I can´t wait to see it growing.

**Comment by broncheolus** [comment]
Sorry to bother you once more and sorry when the following is a stupid suggestion:
 Would an additional small App (i.e. Fernschreiber-Notifier) that adds the sound functionality, be an option? (only on OpenRepos) So one could work around the possible API restrictions. Don´t know if that´s possible from the programmer´s point of view without too much effort. (patch or separate app)

**Comment by monich** [comment]
I remember about this one. But so far I can only repeat what I said earlier - it's probably not a big deal, could be as simple as setting [HINT_SOUND_FILE ](https://git.sailfishos.org/mer-core/lipstick/blob/ee163751/src/notifications/lipsticknotification.h#L87)for the notifications and making it configurable. You're just a bit unlucky that active developers don't seem to be big fans of notification sounds and don't feel the urge to do it ASAP. It's a hobby project, after all.

Periodic gentle reminders do increase the chance of it being done at some point.

**Comment by broncheolus** [comment]
Didn´t want to "push" ;-)) you. It´s sooo great that there are developers like you all, just wanted to play with some thoughts. Keep on going, sailfish is worth it.

**Comment by Wunderfitz** [comment]
OK folks, constant inbox bombing really makes a difference. ;) Seems that we don't even need to specify the sound file, but can use standard, built-in stuff. If no critical showstoppers appear, you will have sound again in 0.7.

Thanks mates, keep on pushing!
