### ISSUE TITLE
Unread count sometimes not cleared even when I answered to that chat

### ISSUE THREAD

**Issue by frefell** [Wunderfitz/harbour-fernschreiber#235]
Sometime the unread count does not get cleared, even when I answered to a chat (i.e. spend "enough" time at the latest message). The last x messages (including my answers) will then be highlighted as unread. 
The unread counter gets cleared, when I reenter the chat, flick to end of conversation and wait 2 sec. 

I can not (yet) reliably recreate this bug, it just happens sometimes, both in single person conversations, but also in group chats. I have not tested it with secret chats.

I am using Fernschreiber 0.51, Sailfish OS 3.4.0.24 on an XA2 (single sim).  
I also have telegram running on my laptop.

**Comment by fridlmue** [comment]
I can confirm, but I cant reproduce at well. I have the feeling(!) that this happens to telegram desktop as well sometimes.

**Comment by Wunderfitz** [comment]
Though I haven't been able to reproduce that yet, that need to be fixed somehow. Maybe it's related to some issues in the TDLib message database and as TDLib will be updated in the next Fernschreiber release (if no additional showstoppers will occur ;)) that might be fixed automatically, but we'll see...

Any additional hints how to reproduce that are appreciated!
