### ISSUE TITLE
making "light mode" more readable

### ISSUE THREAD

**Issue by yusssufff** [Wunderfitz/harbour-fernschreiber#239]
It would be great to have a more readable chat in "light mode"...
You can test with Jolla's "Glacial" theme for a few hours to see what i mean;)

**Comment by Wunderfitz** [comment]
I think I get what you mean - are you referring especially to the own messages, right? The contrast should be much better here, I suppose.

**Comment by yusssufff** [comment]
Yes absolutely right, own message (while writing it and after sending it). Contrast issue yes.

**Comment by Wunderfitz** [comment]
I tested a bit back and forth and at least to my eyes, the coloring of the message bubbles are the culprit. I adjusted them for light ambiences, will be included in 0.6...
