### ISSUE TITLE
"mark as unread" option in the main chats page

### ISSUE THREAD

**Issue by yusssufff** [Wunderfitz/harbour-fernschreiber#240]
It would be great would be to add ''mark as unread'' to ''mute chat and user info'' when long pressing on one chat in the main chats page

**Comment by Wunderfitz** [comment]
Please see #70 - mark as unread doesn't seem to be supported. Moreover, I'm wondering what you want to mark as unread if you want to perform the action on the chat itself - all probably 1000s of messages?

**Comment by yusssufff** [comment]
Hi!
Well both in the android app or on the Sailfish's "Depecher" app, each chat can be ticked as either "read" or "unread"...
This in an option on the main chat list... lets say you were reading a message from someone, you may want to tick that chat as unread to let it stand out as "unread" to remember to answer it later for exemple...

**Comment by Wunderfitz** [comment]
Ah yes, thanks for the additional information. Seems that there is indeed a dedicated option for this. In this case reopening this one and changing the label accordingly.

Details: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1toggle_chat_is_marked_as_unread.html
