### ISSUE TITLE
landing on last message directly when opening a chat

### ISSUE THREAD

**Issue by yusssufff** [Wunderfitz/harbour-fernschreiber#243]
It would be great to land on the last message directly when opening a chat (it is already better with latest versions of Fernschreiber) so not to have to scroll down immediately after opening a chat...

**Comment by monich** [comment]
First unread, I would say. And it actually seems to land pretty close to it already (like, last read message, you only need to scroll down a little bit).

**Comment by Wunderfitz** [comment]
I'm honestly really happy with the status quo and if there is a change in behavior, I'd like to have it configurable. So, please don't expect any changes here from my end in the near future, but - as always - contributions are welcome! :)

**Comment by yusssufff** [comment]
Well on my device, when i open a chat it lands as Monich funnily says "pretty close" to the last message:).
But there isnt really folling a rule that i could understand. Sometimes it lands on last message sent, sometimes on the last recieved, sometimes a bit more up, sometimes in the middle of a message...
Truly said there isnt much to scroll down (It used to be much more problematic a lot of couple of Fernschreiber's versions ago), but its just a repetitive  move of scroll down each time of opening a chat....
