### ISSUE TITLE
replacing emoji search shortcut '' :< '' by " :~ "

### ISSUE THREAD

**Issue by yusssufff** [Wunderfitz/harbour-fernschreiber#244]
In order to use the emoji search, Fernschreiber implemented a solution needing to type ":<>”.
With Jolla keyboard, in order to type :< you need to go to the second raw of keyboard which is a bit longer and less fast and intuitive that would  :~ be...

**Comment by lal883** [comment]
Don't think you need to type "<", I understand it as just the colon followed by emoji name/mood.

For instance, to insert a smile emoji, I could search a list of relevant emojis by typing ":sm" (the first two letters of the word smile).

Another note though, typing the whole word ":smile" shows a totally non-relevant emoji on my device.

**Comment by yusssufff** [comment]
Ah you are right i noticed now that just ":" seems enough to trigger the emojis!!!

**Comment by Wunderfitz** [comment]
@yusssufff: Not sure if I want to change it ':' is a nice one (and also used by other apps/services to insert emojis). Moreover, on my keyboard (German layout) I don't even have any additional keys beyond ',' and '.', so I'd also need to switch to the second raw if we used '~'.

@lal883: Right now, I'm only using the 'official' descriptions for emojis to search/find them. Most emojis in question seem to have "smiling" in their description. If you enter "smile" no match is found. Of course, there are some possibilities to solve that problem, but that still needs to be implemented. ;)

**Comment by lal883** [comment]
Ah I wasn't aware of such standard a description for emojis. Much easier now, thanks for that information. Thought it worked by entering the mood 😀

**Comment by yusssufff** [comment]
Yes lal883 enlightened me that the '<' cartacter wasnt needed, and that ':' was enough!
So as you write, Wunderfitz, there isnt a point any more to keep this 'isse', i think the topic can be closed!
