### ISSUE TITLE
Old message keeps showing up with each fernschreiber start

### ISSUE THREAD

**Issue by andywuest** [Wunderfitz/harbour-fernschreiber#265]
Hi,

i have the problem that with each start of fernschreiber an old message keep showing up. It is always the same and i do not know
how to get rid of this message. it is now more than 2 months old - and i have no idea why it shows up with each start. I think it was a response to one of my posts in the german Sailfish OS Community telegram channel. 
In the log file i cannot see anyhting suspicious when i start the app via the cli. The log is rather short :-( i am using version 0.5.1 with SFOS 3.4 on a XA2 Plus.

![old_message_keeps_showing_up](https://user-images.githubusercontent.com/644248/103464089-9694c300-4d31-11eb-9c24-46074aece179.png)

**Comment by Wunderfitz** [comment]
Yep, there was an issue with mentions in group chats, there were not cleaned up properly. This was fixed with e6fd5885aae45ef61edb40ba753d21acab46ec53 and will be part of 0.6. Until this version is released, you can mark this mention as read in another client (e.g. Telegram Desktop).
