### ISSUE TITLE
Open Chat Scroll Position: Own unread Messages

### ISSUE THREAD

**Issue by jgibbon** [Wunderfitz/harbour-fernschreiber#271]
I've found a specific variant of the closed and pretty general #1.

To reproduce it, you just have to spam a bit without your messages being read by the other side. 
When re-opening the chat, it will only be scrolled down to the last read message, not your most recent. 

At least this happened to me reproducible in both a private chat and a (basic) group chat.

**Comment by jgibbon** [comment]
This may or may not be the thing mentioned in the comments of #243, but I've understood #243 as a different thing/feature request.

**Comment by yusssufff** [comment]
The overall #243 issue is the sort of "random landing" when opening a chat...
Usually landing pretty close to last message but often a few messages above.... 
S when opening a new chat first thing is often the need to scroll down.
At least on my device (xa2).
I couldnt find an exact "logic" for this "almost last message landing".... Sometimes it is last read, sometimes last recieved...
Interestingly Depecher always lands on last message for example.
