### ISSUE TITLE
See the "shared media" in the user details

### ISSUE THREAD

**Issue by yusssufff** [Wunderfitz/harbour-fernschreiber#273]
Right now in the user detail pages, one can see mostly "common groups" (plus a phone number, a profile picture).
In its last update, Depecher implemented on that page the whole "shared media" details (all photos in common, links shared, and so on....Quite like the android app).
Maybe that code could be copied over to Fernschreiber?

**Comment by Wunderfitz** [comment]
Duplicate, already requested in #145.
