### ISSUE TITLE
Add an "Emoji picker" (near the sickers picker in the "attach" menu) 

### ISSUE THREAD

**Issue by yusssufff** [Wunderfitz/harbour-fernschreiber#274]
Fernschreiber is displaying very smoothly emojis.
It is also possible to pick emojis with the ":<>" shortcut.
But considering that the native emoji list on Jolla's keyboard is limited, why not to implement an "emoji picker" near the sticker picker?
That would display an exhaustive page of pickable emojis, more extensive than the Jolla keyboard ones...
Maybe on top of that grid would be the "most used" emojis and so forth...

**Comment by Wunderfitz** [comment]
The pickers are for attachments or similar message components (such as stickers). The :<keyword> feature is just for convenience reasons and I wouldn't want to go beyond that. Inputs for text messages should mainly be handled via the respective keyboards, such as Emoji+ (https://openrepos.net/content/ade/emoji-keyboard). If things are done there, all applications could profit.

**Comment by yusssufff** [comment]
Ok i see!
Well for non openrepos user, that could have been handy...

**Comment by yusssufff** [comment]
Maybe it worth to notice that in the "official" Telegram android app for exemple the emojis are "included in the app", they are not the "standart Android emojis" that comes with phone's keyboard, but instead Telegram's own emoji picker... The same goes with the Tdlib-using "Telegram X" which allows even users to pick betwen different emoji packages (twitter's, apple's and so on).

**Comment by yusssufff** [comment]
Thank you for the long answer! Very instructive!
Well but what about just creating an "attachement" link to the twemoji project emojis?
Basically what happens with the :<> feature, but with a full grid of the twemojis (easier to pick that guessing a keybord after ":")...
What would you think of such pathway?

**Comment by Wunderfitz** [comment]
As said: If somebody wants to provide something like that (I'd still rather see something like that as a keyboard for all SFOS apps), I'll have a look, but it's still out-of-scope for Fernschreiber right now.

**Comment by yusssufff** [comment]
thanks for the reply!
Yes i think i understood your point about this topic.
Just one last point: You mention that if someone would provide something, you'd have a look at it, but isnt the ''closed'' status of this issue putting it ''far from eyes''?

**Comment by yusssufff** [comment]
From Sailfish 4, still no sign of more emojis implemented by jolla....
And okboard itself is a blocker for the update (jolla specifically asks to uninstall it in the Koli upgrade notes), therefore hard to recommand to non cautious tech users...
