### ISSUE TITLE
app cover UI: Making the number of unread messages size larger

### ISSUE THREAD

**Issue by yusssufff** [Wunderfitz/harbour-fernschreiber#275]
Fernschreiber's app cover is quite clean.
Just the number of unread message and connection status... That is very nice not to have put a "branding" name here.
I just considered that it could be nice to enhance the size of the "number" of unread messages.
The eye when quickly peeking on the phone is looking for that number.
I'd assume that enhancing a bit the number's font size would make it easier for the eye catch...

**Comment by Wunderfitz** [comment]
The sizing of the elements on the cover page follows the ones also applied in stock apps, especially the e-mail client. By default Fernschreiber will keep this sizing, but further configuration options are probably the way to go. Please follow-up in #23 where other ideas are already posted. Configuration of the cover page UI can be added to the wishlist as well.
