### ISSUE TITLE
"open-with menu integration" sticking in Sailfish after uninstalling the app

### ISSUE THREAD

**Issue by yusssufff** [Wunderfitz/harbour-fernschreiber#276]
The "open-with menu intergration" is not getting deleted if you uninstall Fernschreiber.
I guess some people will not be happy with the app and uninstall it.
Then they have the "open with Fernschreiber" leftover in their phones (can make some people quite annoyed...).
The way to get rid of it isnt very complicated of course (download again the app, then untick "open-with menu integration" then uninstall app again).
But its a small detail that can annoy some users.... Or maybe should that option be unticked by "default"?

**Comment by monich** [comment]
Cleaning up after uninstall could be simple enough with an rpm scriplet like this:

```sh
%postun
if [ "$1" == 0 ] ; then
  for u in $(getent passwd | cut -d: -f1); do
    delete the crap under $u ||:
  done
fi
```

But scriplets are not allowed in Jolla Store 😕

**Comment by yusssufff** [comment]
I see... Maybe then "open with menu integration" shouldnt be "ticked on" by default?
So if the user took the time to tick it, he/she can remember to untick it when that "leftover" situation happens...?

**Comment by Wunderfitz** [comment]
Well, that's one of the limitations of the platform, sad but true. Harbour compatibility won't be sacrificed (at least not by default, if somebody integrates a two-way build...OK). 

We had this discussion already in #151, probably we need to integrate a dialog at startup to ask people if they want to have the integration in the open-with menu. That's not top priority right now, but if somebody wants to contribute that, it would certainly be appreciated. No matter what, please follow-up in #151 as it was already posted some time ago.

**Comment by attah** [comment]
Just FYI, this is still borked.
And it breaks the system: https://forum.sailfishos.org/t/opening-a-bookmark-from-app-grid-seems-to-be-broken/5779

Wouldn't x-url-handler be better?

**Comment by jgibbon** [comment]
This seems to belong to a bunch of related issues:  #151, #276, #312, #412 (this comment is copied to all of them)
Proposed way to hopefully fix most of them:
 - use [`MimeType=x-url-handler`](https://forum.sailfishos.org/t/sailfish-community-news-11th-march/5409) (caveat: according to link, `update-desktop-database` isn't called after installation yet…)
 - implement at least some of the missing url functions (link in #312 – search for `LocalUrlHandlers`; also look below)
 - on start: scan for existing .desktop file, delete.
 - link handler: save "active link" to some temporary property until tg is authenticated, only then process it.
