### ISSUE TITLE
Sticker picker initialization/loading performance

### ISSUE THREAD

**Issue by ferlanero** [Wunderfitz/harbour-fernschreiber#286]
No matter how many sticker packs you have loaded in Telegram, Fernschreiber loads it at incredible low speed. At the same point I have to admit that once sticker menu is loaded everything flows as expected.

**Comment by Wunderfitz** [comment]
FYI, it shows the spinning wheel until all sticker preview icons are loaded. Theoretically, the app could show the overview immediately, but that would lead to each preview icon pop up individually. Any preferences here?

**Comment by jgibbon** [comment]
I think having them fade in may be sufficient to make interaction possible way sooner. 

Sounds like a "low effort, high return quick fix" to me.

**Comment by ferlanero** [comment]
> FYI, it shows the spinning wheel until all sticker preview icons are loaded. Theoretically, the app could show the overview immediately, but that would lead to each preview icon pop up individually. Any preferences here?

I think the option to overview stickers immediately would be better than waiting to see everything loaded which seems to slow down the whole app
