### ISSUE TITLE
Last Fernschreiber update doesn't show videos in full screen

### ISSUE THREAD

**Issue by ferlanero** [Wunderfitz/harbour-fernschreiber#290]
I can see video broadcasting with no problem inside the own chat timeline, but when I choose the full screen option, I can see nothing except the Fernschreiber logo

**Comment by Wunderfitz** [comment]
Yep, also noticed it this morning, is already fixed with 7e6c8712613a4105eb83d20bd58d9dfafac7abf0 and will be in the next patch release 0.6.1.
