### ISSUE TITLE
Feature Request: Multi account support

### ISSUE THREAD

**Issue by gibcheesepuffs** [Wunderfitz/harbour-fernschreiber#298]
Allow to login and manage more than one account.

**Comment by Wunderfitz** [comment]
Duplicate, was already requested in #71

**Comment by Wunderfitz** [comment]
Reopening as #311 really only implements logout/login. Real multi-user support is a little more than that...

**Comment by sleepycrow** [comment]
Was this actually completed? I might be overlooking something, but I can't seem to find any options to log into another account... P;
