### ISSUE TITLE
Initial authentication impossible in landscape

### ISSUE THREAD

**Issue by Wunderfitz** [Wunderfitz/harbour-fernschreiber#3]
Seems that scrolling is not possible during initial authentication (enter PIN and password). Therefore people need to switch to portrait during initial authentication. Should really be fixed... ;)

**Comment by jgibbon** [comment]
Should be possible since 0.3

**Comment by Wunderfitz** [comment]
Yep, just checked it on my Gemini PDA. @jgibbon's changes were really the solution! :)
