### ISSUE TITLE
New messages are not shown on Xperia X

### ISSUE THREAD

**Issue by 24mu13** [Wunderfitz/harbour-fernschreiber#304]
On my phone (**Xperia X**) new messages are not displayed correctly: I always need to scroll a bit down.
Sounds like you calculate using another display (XA2/10?), maybe hard-coded height?

Not sure, I will gather new details using emulators; but please let me start writing down from an user perspective.

## How to reproduce:

1. A friend texts me (could be also a new message in a group/channel)
2. I tap to that friend and I am positioned to the bottom of the conversation, but WITHOUT seeing latest message 
3. I scroll a bit down, and here I am: his latest message

<img src="https://user-images.githubusercontent.com/14576296/104122282-6b6b2e80-5344-11eb-9977-5b987a1af1aa.jpg" width="300"/> <img src="https://user-images.githubusercontent.com/14576296/104122294-7f169500-5344-11eb-9a4f-30b0d6eb953f.jpg" width="300"/>

**Comment by 24mu13** [comment]
Really sorry but despite my search I din't found this issue that is very similar: #271

**Comment by Wunderfitz** [comment]
I have to admit I didn't understand your explanation... What you mean could also be described already to #243 - no matter what, please try to add your issue in the best fitting issue. IMHO there is no need to open a third one. ;)
