### ISSUE TITLE
Improve Fernschreiber icon

### ISSUE THREAD

**Issue by GNUuser** [Wunderfitz/harbour-fernschreiber#31]
Sorry. Currently the content of the icon looks like a shopping bag, as a result it refers to an icon to apps-store and not  much to a Telegram client, It would also be better if you explain the content of the Fernschreiber icon to understand it better.

**Comment by Wunderfitz** [comment]
Well, I'm really open to new icons, please send propsals if you have any. ;)

Concerning the icon - I was thinking of some radio signals and a teleprinter punched tape Baudot-Murray code (https://en.wikipedia.org/wiki/Baudot_code) encoding "TELEGRAM"...

**Comment by GNUuser** [comment]
Ok the content of the icons is good, the problem is in the radio signal, may be moving the signal to other side looks better. 
The orange color have a means something?

**Comment by Wunderfitz** [comment]
No, I simply like orange - and I used blue far too much in my other apps. ;)

**Comment by iamnomeutente** [comment]
I'm not a graphic designer, but I tried to modify your icon.
Here is my proposal :)
It is based on the Sailfish OS guidelines. Orange and code are still there, the form reminds of a speech balloon. 
 
![harbour-fernschreiber-2](https://user-images.githubusercontent.com/72705765/95729266-f15fd680-0c7c-11eb-90b4-107ce9ac716c.png)

**Comment by Wunderfitz** [comment]
That actually looks pretty cool! Thanks! Maybe I'd play with the colors a bit and move the code a bit up, but we could really use it.

Would you mind sending me the original image (e.g. in vector graphics format)?

**Comment by GNUuser** [comment]
Looks ok, why not do the Telegram Triangle logo with Baudot_code??

**Comment by Wunderfitz** [comment]
@iamnomeutente Oh, thanks, but I will definitely mention you. :) Please send it to sebastian@ygriega.de
@GNUuser Third-party clients are not allowed to use anything that resembles the original logo...

**Comment by Wunderfitz** [comment]
Thanks again for the great design @iamnomeutente and of course also for the issue, @GNUuser - the new icon is already in the repo and will be part of 0.3. :)

**Comment by GNUuser** [comment]
Thank you: @Wunderfitz @iamnomeutente

**Comment by iamnomeutente** [comment]
I'm happy you liked it ;)
