### ISSUE TITLE
Poll-Summary are showing no results

### ISSUE THREAD

**Issue by Clint86** [Wunderfitz/harbour-fernschreiber#331]
The poll summary of an non-anonymous poll don´t show results of who chose what.

![photo_2021-01-21_17-14-33](https://user-images.githubusercontent.com/76128955/105386504-c4747580-5c14-11eb-829d-b37b40042177.jpg)
![photo_2021-01-21_17-15-05](https://user-images.githubusercontent.com/76128955/105386507-c5a5a280-5c14-11eb-9382-9efde1fde072.jpg)

**Comment by jgibbon** [comment]
Will be a simple fix – we just renamed a variable at some point but forgot to do it where the detail page is opened. 
I'll see if I can also add some tdlib 1.7 features, as well, when I get to it.
