### ISSUE TITLE
Can't join group

### ISSUE THREAD

**Issue by okruhliak** [Wunderfitz/harbour-fernschreiber#338]
The button Join Group did not respond when trying to join the group. This message was in the console FF:
`Prevented navigation to “tg://join?invite=CdK7IU5DD9IdMuswrlY4tQ” due to an unknown protocol.`
![Mozilla Firefox](https://user-images.githubusercontent.com/47862310/105704300-e3258580-5f0e-11eb-9052-27b414517895.png)

Can you help me, please?

**Comment by okruhliak** [comment]
The reason was that I did not have the Telegram application installed on my PC. I have already connected with the group in Telegram.

**Comment by jgibbon** [comment]
In case anyone else gets this: There should also be another Button "Open in Web".
