### ISSUE TITLE
A group which I left remains in the list

### ISSUE THREAD

**Issue by monich** [Wunderfitz/harbour-fernschreiber#34]
Checked from another, more functional client - I'm no longer a member. But the group is still there.

In addition to that, there are some groups/channels in the list which I don't remember to ever being subscribed to.

That's a) garbage and b) inefficient, as all this useless information is being pulled from the network and maintained by the client for no good reason.

**Comment by Wunderfitz** [comment]
Mhmm, the app doesn't explicitly retrieve chats the user left. It relies on TDLib getting the chats and simply displays them. I also haven't found an attribute (yet) that tells me whether the user left this chat... Well, maybe I need to dig a little deeper...

However, it is very likely that it doesn't react properly if you leave the chat during the app is running, that can certainly be implemented easily. Was that the case, i.e. did you leave the chat while Fernschreiber is running and is the chat still there if you restart Fernschreiber?

**Comment by monich** [comment]
No, that was a chat that I left long time ago. Restarting the app doesn't change anything. There were chats which I never joined in the first place. It's possible though, that messages from those chats were forwarded to the chat(s) which I joined, does that ring a bell?

In other words, I seem to be seeing two kinds of rogues chats in the list:

1. I join chat X, leave chat X, chat X remains in the list (that's definitely happening)
2. I join chat A, message from chat B is forwarded to chat A, I start seeing chat B in the list (suspected scenario)

**Comment by monich** [comment]
Just thought that it might be an interesting and somewhat even useful feature - a special mode "all chats which you have ever touched in your entire life". It's just that it shouldn't be the default and it must be possible to turn it off, otherwise the client becomes pretty much unusable. It's not one or two, I seem to have over a hundred of extra chats in the list, in addition to 20-30 which I actually use.

**Comment by monich** [comment]
Hmm, I have slightly rewritten `ChatListModel` (mostly with optimization purposes) and those rogue chats disappeared :/ I'll test my changes a bit more and submit a patch.

**Comment by monich** [comment]
Actually, a few of them are still there. Weird.

**Comment by monich** [comment]
[This patch](https://github.com/Wunderfitz/harbour-fernschreiber/pull/45) resolves the issue for me.

**Comment by monich** [comment]
Now that my patch has been merged, I guess this one can be closed. Or do you want to close it after baking the next release?

**Comment by Wunderfitz** [comment]
Ah, completely forgot. Good, let's close it! :)
