### ISSUE TITLE
Suggestion to refine the translation in the CoverPage section in Slovak

### ISSUE THREAD

**Issue by okruhliak** [Wunderfitz/harbour-fernschreiber#351]
I have a suggestion to refine the translation in the CoverPage section.

At present, it is as follows

```
    <name>CoverPage</name>
    <message>
        <source>unread message</source>
        <translation>neprečítaná správa</translation>
    </message>
    <message>
        <source>unread messages</source>
        <translation>neprečítané správy</translation>
    </message>
```

Thus, it is not possible to fulfill grammar in Slovak, because there is only the singular and the plural, but Slovak distinguishes 3 forms:
- 1 unread message {1 neprečítaná správa}
- 2-4 unread messages {2-4 neprečítané správy}
- 0, 5-N unread messages {0, 5-N neprečítaných správ}

```
    <message>
        <source>unread message</source>
        <translation>neprečítaná správa</translation>
    </message>
    <message numerus="yes">
        <source>unread messages</source>
        <translation>
            <numerusform>neprečítaná správa</numerusform>
            <numerusform>neprečítané správy</numerusform>
            <numerusform>neprečítaných správ</numerusform>
        </translation>
    </message>
```
Would it be possible to adjust it, please?

**Comment by Wunderfitz** [comment]
Absolutely right, it's fixed with 3bc97f27394d3509fd1c17170a815734378b0759
