### ISSUE TITLE
Display shared Locations

### ISSUE THREAD

**Issue by jgibbon** [Wunderfitz/harbour-fernschreiber#36]
Hi,
I'd like to take a look at adding this, but obviously don't want to implement stuff you wouldn't like.
Please let me know what you think about these points or if you'd even like me to have a go at this to get my feet wet with Fernschreiber:

### General
There are only a few ways to implement showing maps, all with pros and cons.
 - Static map images: While not very resource intensive, the only online service I found that doesn't require an API key is yandex. It only supports small images. But even with other services, I see possible privacy concerns.
- QT Location: Pretty resource intensive (perhaps too much so to integrate into the chat list), also obviously not harbour compliant. For the detail view, it may still the best option **if you do not plan to submit fernschreiber to the Jolla Store**. There could be a possibility to set user-defined OSM-Tile-URLs in the options, too. (If you like, I could also adapt the settings ui from Talefish in case there'll be a lot of options at some point – but that's another topic)

### Chat List (LocationPreview)
 - While static map images would work (it's an image, after all), it may not be desirable for users to send location data to yandex/google/…
 - As mentioned above, displaying a "real" map would be pretty but _could_ get a bit problematic performance-wise.
 - Just displaying a Button (to get to the LocationPage) with the adress doesn't work – reverse geocoding seems to be broken with osm and/or the available QT Location library. Displaying the coordinates or even "Show Location" instead would be fast/easy, but a bit ugly.
 - Another option would be a Button by default with an option to use a (yandex?) map image in the application settings.

### Detail view (LocationPage)
 - Using a Map from QT Location is relatively straight forward. A slight problem is accidentally going back in the PageStack while swiping around. This can, to a degree, be mitigated by disabling "back navigation" on the page for a while when the map center is changed.
 - I don't know yet how to handle message updates for live locations, haven't had a look this deep.
 - While it would be nice to have all currently shared live locations of a chat displayed on one map, I think it's okay not to do that at least initially.

Feel free to get in touch via Telegram, as well, to discuss things if you want to.

cheers,
"velox"

**Comment by Wunderfitz** [comment]
Adding location support is definitely in my head, so if you want to get your feet wet with it, why not? ;) I completely share your concerns regarding privacy and I also haven't made up my mind yet what's the best option. Jolla Store would be a big plus, but Fernschreiber isn't Harbour-compliant anyway at the moment (TDLib compiles with some paths within the binary which the validator doesn't like. Moreover I use NGFD to get the notifications properly done - which isn't whitelisted). In an ideal world, I'd simply perform a DBus call to invoke a third-party map application to display the exact location if the user taps on a static preview. Maybe Poor Maps already supports that... That would basically solve the problem and there is much less code in Fernschreiber (which needs to be maintained).

As a start, I'd recommend using a static image and then build on top of additional iteration. I saw a nice TDLib method which probably already returns the static image, see https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_map_thumbnail_file.html. No idea if and how it works, but that's the thing I'd use to get started. :)

**Comment by jgibbon** [comment]
Quick planning update: 
I've had a quick look at **Pure Maps** yesterday evening, which is the only maintained one in the native sfos maps family (AFAIK!). 
While it doesn't have a DBus service on Sailfish OS (Interface only available at runtime), it supports being run with a [geo uri](https://en.wikipedia.org/wiki/Geo_URI_scheme) command line argument. Adding a Launcher class shouldn't be a problem, also QML could easily pop up an AppNotification if it's not installed. 
With that in mind, we can do without a LocationPage or QT Location  – especially if the TDLib preview image works. 

Food for thought: 
Updating live locations automatically wouldn't be trivial to do from a UX perspective (the active pure maps session opens in the foreground every update or a new one opens if it's not running) in the long run. 
But I think the benefits of not having to care for a maps stack speak for themselves.

cheers!
