### ISSUE TITLE
Randomly add chat(s) from searches

### ISSUE THREAD

**Issue by okruhliak** [Wunderfitz/harbour-fernschreiber#371]
Scenario
1. From the main screen, select Search Chats
2. Have some text searched
3. A list of matching chats is displayed
4. Return to the main screen without selecting anything from the search list
5. One (first?) from the search list will be added to the list of my chats
6. Tried twice, first it add  one chat, then 3 more
7. Restart removes them again

**Comment by Wunderfitz** [comment]
Fixed with 08b004f6a5d502d70532dac7e2560b81a7a2a716, thanks for reporting it.
