### ISSUE TITLE
L10n: Localisation guideline

### ISSUE THREAD

**Issue by iamnomeutente** [Wunderfitz/harbour-fernschreiber#379]
Hi, I found this [guideline](https://sailfishos.org/wiki/Translate_the_OS), maybe it is useful for us for a even better/SailfishOS-like language usage. 
For the Italian one I would remove e.g. I think nearly all full stops. 
Maybe also for German it could be more informal du instead of Sie (duzen). And so on...
What do you think?

**Comment by Wunderfitz** [comment]
I know this guideline and yes, I violated it in several areas, especially in German. Strictly speaking this guideline only applies to wording and translations of the OS and not for apps. ;) Moreover, I really hate that my devices use informal speech in German, so I want to keep the format language at least in my apps. But I'm anyway open to changes here and there and I leave especially all translators complete freedom which style they want to use. It's their work, so they decide. :)

**Comment by iamnomeutente** [comment]
Ok, I close this issue ;)
