### ISSUE TITLE
Fernschreiber interprets '<' in Fernschreiben (maybe a bug)

### ISSUE THREAD

**Issue by FrankBS** [Wunderfitz/harbour-fernschreiber#39]
Could it be, that Fernschreiber interprets '<' i a text?
![Screenshot_2020-09-30_14-52-16](https://user-images.githubusercontent.com/3144625/94687854-196e4200-032d-11eb-89ef-824c638570b1.png)
![Screenshot_2020-09-30_14-55-44](https://user-images.githubusercontent.com/3144625/94687855-1a06d880-032d-11eb-824a-9d70e6d146fb.png)

**Comment by Wunderfitz** [comment]
That was already fixed with 5b0c3df4d341a5e1b6712e5f513c7753a08d535f, see also #29. New version 0.2 with the fix will be out soon(tm).

**Comment by FrankBS** [comment]
#29 ist viel schöner ausgedrückt. Danke.
