### ISSUE TITLE
FeatureRequest: aarch64

### ISSUE THREAD

**Issue by GNUuser** [Wunderfitz/harbour-fernschreiber#403]
Hi Sailors
SailfishSO 64bits could be out soon on pinephone, so can you do a build for aarch64 to next version v0.8.1 please.

**Comment by Wunderfitz** [comment]
Build is now available with 0.8.2, see https://openrepos.net/sites/default/files/packages/12349/harbour-fernschreiber-0.8.2-1.aarch64.rpm

Feedback is really appreciated as I don't own any aarch64 device...

**Comment by GNUuser** [comment]
Many many many many many thank you for adding aarch64. You the best!
