### ISSUE TITLE
Open channel keeps scrolling and marking messages as read even if app is not active

### ISSUE THREAD

**Issue by b100dian** [Wunderfitz/harbour-fernschreiber#410]
If you leave a discussion open in fernschreiber and you either lock the phone or switch to another app, the new replies keep getting scrolled to and marked as read. 
This means that you actually lose notifications of that conversation.

A test for app active-ness is probably needed.
Thanks!

**Comment by Wunderfitz** [comment]
Oh yeah, sometimes the auto-scroll goes crazy, will take a look...

**Comment by Wunderfitz** [comment]
Fixed with 388ea83e45f3a40d5c4dcc729111daa4c8ece795 (will come in v0.9)

**Comment by b100dian** [comment]
Very nice, thank you:)
