### ISSUE TITLE
Opening a Telegram channel displays at least one error message before actually working

### ISSUE THREAD

**Issue by ddobrev** [Wunderfitz/harbour-fernschreiber#412]
I use Sailfish 4.0.1.48 with the latest Fernschreiber. When I've loaded https://t.me/aurorasupport/ in the Sailfish browser and tap "View in Telegram", I get this error: "Initialization parameters are needed: call setTdlibParameters first". When I go back to the browser and tap again, it works. Although there was one occasion, with another group I cannot remember, when the second time I got a second error about some database and checking encryption. The third time finally worked. None of these issues occur with the desktop Telegram client for macOS only.

**Comment by jgibbon** [comment]
This seems to belong to a bunch of related issues:  #151, #276, #312, #412 (this comment is copied to all of them)
Proposed way to hopefully fix most of them:
 - use [`MimeType=x-url-handler`](https://forum.sailfishos.org/t/sailfish-community-news-11th-march/5409) (caveat: according to link, `update-desktop-database` isn't called after installation yet…)
 - implement at least some of the missing url functions (link in #312 – search for `LocalUrlHandlers`; also look below)
 - on start: scan for existing .desktop file, delete.
 - link handler: save "active link" to some temporary property until tg is authenticated, only then process it.
