### ISSUE TITLE
media album message display (was: Multiple photos chat bubble)

### ISSUE THREAD

**Issue by dashinfantry** [Wunderfitz/harbour-fernschreiber#413]
Feature request:
group all photos in a chat bubble can make it tidy and clean especially when we have to send multiple photos from telegram at the same time.
Display them in a big bubble when someone send a lot of photo to a chat in a short time.Fernschreiber will combine all of its photos to a big chat bubble.

**Comment by jgibbon** [comment]
See #554 for the implementation and zipped rpms to try out (please provide feedback if you do)
