### ISSUE TITLE
Chat scrolls a bit up after sending a message

### ISSUE THREAD

**Issue by patrickjane** [Wunderfitz/harbour-fernschreiber#418]
When a new message is sent, the keyboard disappears and the chat scrolls a bit up, right to the point where the newly sent message is not visible anymore. This makes you immediately scroll down after sending a message.

Fernschreiber should instead scroll to the very bottom after a new message has been placed. Maybe this is also a timing issue (Fernschreiber scrolls to the very bottom before the new message has been placed).

The same thing happens when the option to not hide the keyboard after sending a message is activated. In this case, scrolling to the bottom will be correct as long as the keyboard is visible, even if you send multiple messages. However as soon as the keyboard is dismissed (tap on send button with empty message), the chat scrolls that tiny bit up again, hiding the last message.

[edit] Now that I think of it, its actually the animation when the keyboard is dismissed, which scrolls to a wrong position. I think it has nothing to do with sending the message.

**Comment by Wunderfitz** [comment]
It's really not related to sending a chat - something was not working properly when the height of the scroll window changed (e.g. when the keyboard is shown or hidden). A small fix is incoming that should address that.
