### ISSUE TITLE
App crash when opening chat (rlottie aarch64)

### ISSUE THREAD

**Issue by patrickjane** [Wunderfitz/harbour-fernschreiber#428]
I have received a message in a chat with a friend, and every time I try to open this very chat, the app crashes. The contact did not cause any problems before, neither did any of the other chats, so I suspect it might have something to do with the sticker that was sent in this last message. 

Meanwhile I have marked the message read with the desktop telegram app, but still Fernschreiber is crashing when opening the chat. I can see the sticker loading, but quickly after the app crashes. The sticker is this one: https://imgur.com/a/DAu0fMb

I have not yet deleted the message via desktop app, so I can help to investigate.

[edit] forgot to mention, most recent version of Fernschreiber (0.9.x) and SFOS 4.1.0.24 on a 10ii.

**Comment by jgibbon** [comment]
Hi, thanks for reaching out.
There are some issues on aarch64 with the library used to display stickers. We don't have a good way to fix that, yet.

To ensure being able to at least continue using Fernschreiber, you can try to enable the "Show stickers as emojis" setting for now.

**Comment by jgibbon** [comment]
Hi, thanks for reaching out.
There are some issues on aarch64 with the library used to display stickers. We don't have a good way to fix that, yet.

To ensure being able to at least continue using Fernschreiber, you can try to enable the "Show stickers as emojis" setting for now.

**Comment by monich** [comment]
https://github.com/Wunderfitz/harbour-fernschreiber/pull/429 fixes those crashes for me. I haven't been able to pinpoint the real root cause, though.

**Comment by jgibbon** [comment]
@patrickjane there is a test build containing #429 on https://github.com/jgibbon/harbour-fernschreiber/releases/tag/pre-settings-test
if you'd like to have a look.
