### ISSUE TITLE
Bug: unable to attach files (videos, images, audios) on jollaphone

### ISSUE THREAD

**Issue by paolomi** [Wunderfitz/harbour-fernschreiber#432]
Hi :) 
On my old jolla phone (sailfish os 3.4.0.24), fernschreiber (version 0.9) cannot attach files (videos, images, audios). There are no relevant errors when run from the terminal. I've waited up to an hour but the upload never completes. 
![attachment](https://user-images.githubusercontent.com/16490957/124990086-33694d80-e040-11eb-946d-9c7499e0cb24.png)

If this phone is obsolete for fernschreiber, to attach files I'll use yottagram as a workaround (attachments work on yottagram). Many thanks :)

**Comment by monich** [comment]
Could it be a temporary glitch? I tried but wasn't able to reproduce this problem on 3.4

**Comment by paolomi** [comment]
Turning off and turning on the jollaphone doesn't help. Any suggestions?

BTW, running from the terminal:

,---
| Sailfish OS 3.4.0.24 (Pallas-Yllästunturi)
'---
[nemo@Jolla ~]$ harbour-fernschreiber 
[D] unknown:0 - Using Wayland-EGL
[ 3][t 4][1625806940.122718095][Td.cpp:4588][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "version"
  value = optionValueString {
    value = "1.7.0"
  }
}
[ 3][t 4][1625806940.123908042][Td.cpp:4588][#1][!Td][&td_requests]     Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitTdlibParameters {
  }
}
[ 3][t 0][1625806940.128453731][Client.cpp:274][&td_requests]   Begin to wait for updates with timeout 5.000000
[ 3][t 0][1625806940.129033565][Client.cpp:282][&td_requests]   End to wait for updates, returning object 0 0x46904920
[ 3][t 0][1625806940.129704475][Client.cpp:274][&td_requests]   Begin to wait for updates with timeout 5.000000
[ 3][t 0][1625806940.129948854][Client.cpp:282][&td_requests]   End to wait for updates, returning object 0 0x46904a78
[ 3][t 0][1625806940.130589246][Client.cpp:274][&td_requests]   Begin to wait for updates with timeout 5.000000
[ 3][t 4][1625806940.137606382][Td.cpp:3449][#1][!Td][&td_requests]     Receive request 1: setLogVerbosityLevel {
  new_verbosity_level = 2
}
[W] unknown:40 - file:///usr/share/harbour-fernschreiber/qml/pages/OverviewPage.qml:40:32: Unable to assign null to QString

[ i've cut the key log as a precaution]

[W] unknown:715 - file:///usr/share/harbour-fernschreiber/qml/pages/ChatPage.qml:715:26: Unable to assign [undefined] to bool
[W] unknown:735 - file:///usr/share/harbour-fernschreiber/qml/pages/ChatPage.qml:735:26: Unable to assign [undefined] to bool

(harbour-fernschreiber:2294): Tracker-WARNING **: 07:02:39.444: Locale 'LANG' is not set, defaulting to C locale
[W] unknown:30 - file:///usr/share/harbour-fernschreiber/qml/components/BackgroundImage.qml:30: TypeError: Cannot read property of null
[W] unknown:30 - file:///usr/share/harbour-fernschreiber/qml/components/BackgroundImage.qml:30: TypeError: Cannot read property of null

**Comment by Wunderfitz** [comment]
Do you still have this issue with the latest version (download from https://openrepos.net/content/werkwolfoldschool/fernschreiber-jolla-phone-and-older-sfos-versions-only)?

**Comment by paolomi** [comment]
> Do you still have this issue with the latest version (download from https://openrepos.net/content/werkwolfoldschool/fernschreiber-jolla-phone-and-older-sfos-versions-only)?

Yes, there is the same problem. and no useful output on the terminal.

**Comment by Wunderfitz** [comment]
Strange... One additional question though: Does the progress bar never appear or is it simply stuck? In the screenshot that you posted above, you haven't sent the message yet. But the upload won't start before you sent the message... 

So, please attach the image/video/whatsoever and send the message. Then please send me a screenshot and have a look at the debug output.

**Comment by paolomi** [comment]
> In the screenshot that you posted above, you haven't sent the message yet. But the upload won't start before you sent the message...

The problem was that I never sent the message! Unlike yottagram, I only found out now that I have to touch the "send" button. 
I'm dying of shame! The bug was in me! I close this one and thanks a lot for everything!
