### ISSUE TITLE
Stickers for selection sometimes are not properly aligned

### ISSUE THREAD

**Issue by andywuest** [Wunderfitz/harbour-fernschreiber#438]
Hi,

the problem is not always reproducable but here is a sample screenshot when it does not look good. I have opened the dialog for the sticker selection -> i have 4 Stick collections added. Some of the "Jean baptiste plague" stick collection have been used lately. Sometimes the Recently Used is hidden by the first sticker in the list - sometimes it is looking ok. not sure if you can reproduce the problem, but see the attached screenshot for yourself.

![fernschreiber_sticker](https://user-images.githubusercontent.com/644248/131390536-4e617a6a-e655-4375-b343-dbb13ae69502.png)

**Comment by Wunderfitz** [comment]
Seems that something is misaligned if no recent stickers have been found (might take a while or even an app restart to sync).
