### ISSUE TITLE
Better handling of deleted contact accounts

### ISSUE THREAD

**Issue by andywuest** [Wunderfitz/harbour-fernschreiber#439]
The original Android Telegram app shows deleted account as "Deleted Account" , however Fernschreiber shows them as "Unknown". It would be nice if Fernschreiber could als display them as "Deleted Account"

In the Android App i have to option to

* Pin to top
* Mark as unread
* Clear history
* Delete

Fernschreiber only allows me to

* Mark chat as unread
* pin chat
* Mute chat
* User Info

=> why is there no option to display the delete account -> it does not make sense for me to have them hanging around and it would be nice if i could remove them in Fernschreiber.

Another strange thing is that i can still view the chats with the "Unknown" contact - so far so good. However, if i go back to the overview i get the notification "Have no write access to the chat" - not sure why i get this one, but i assume that it does not make sense to display this notification for deleted accounts.

**Comment by Wunderfitz** [comment]
To my knowledge there is no attribute/status that tells apps if a user was deleted or not - so it simply displays missing information (of whatever kind) as "Unknown". But at least the obvious bug with the message should be fixed - if I implement destructive actions that go beyond deleting single messages - let's see... ;)
