### ISSUE TITLE
Impossible to install Fernschreiber after Sailfish OS upgrade to 4.3.0.12

### ISSUE THREAD

**Issue by aklapper** [Wunderfitz/harbour-fernschreiber#448]
Before upgrading Sailfish OS from 4.2 to 4.3, system told me to uninstall Fernschreiber:  “Remove or revert the following package, as it may cause problems during update: harbour-fernschreiber”. After upgrading to 4.3.0.12, Trying to reinstall from the Jolla Store, `journalctl` shows `Wrapped transaction failed: "could not find package harbour-fernschreiber"`.

The same issue has been pointed out in the Jolla Store feedback for this application by others.

**Comment by Wunderfitz** [comment]
Version 0.10.1 is in Harbour QA. If they don't find any showstoppers, it should be in the Jolla Store pretty soon. If it's urgent, please check out https://openrepos.net/content/werkwolf/fernschreiber. I'll keep this issue open until the new version is in the Jolla Store.

**Comment by Wunderfitz** [comment]
Fernschreiber 0.11 is now also available in the Jolla Store. As the new version should work again after the major Telegram server update, I'm closing this issue.
