### ISSUE TITLE
Unable to register new device, UPDATE_APP_TO_LOGIN, update tdlib?

### ISSUE THREAD

**Issue by the-real-ed** [Wunderfitz/harbour-fernschreiber#451]
Thanks for your work on this application.

I encountered this issue while attempting to register my new XA2 device with SailfishOS 4.3.0.

On first launching Fernschreiber, I'm asked to enter my phone number, which I do, and then submit/commit/continue. I get a brief error message "UPDATE_APP_TO_LOGIN", while the progress spinner runs.

It appears that this may be related to the tdlib library which may require upgrading (see https://github.com/tdlib/td/issues/1758).

I'm running the latest version of Fernschreiber, 0.10.1

**Comment by Wunderfitz** [comment]
Yes, I'm aware of this situation - happened to anyone yesterday or the day before already. I already have the new version running here locally - just need to compile it for all platforms (aarch64, armv7hl, i486, armvlhl[openssl10]) and test a bit. Looks promising so far. Hope, I have a new version ready tonight.

**Comment by Wunderfitz** [comment]
Release 0.11 is on OpenRepos and hopefully soon in the Jolla Store. For the time being, I keep this things open for feedback. :)

**Comment by the-real-ed** [comment]
Thank you, I can confirm that 0.11 resolved the issue for me. I was able to register the new XA2 device.

**Comment by lota** [comment]
thx! 0.11 works fine also for me on Xperia XA2 Sailfish OS 4.3

**Comment by Wunderfitz** [comment]
Closing then, thanks for the feedback.
