### ISSUE TITLE
Impossible to install Fernschreiber from 0.10-1+ on Jolla Phone running Sailfish OS 3.4.0.24

### ISSUE THREAD

**Issue by iamnomeutente** [Wunderfitz/harbour-fernschreiber#459]
Hello, I can't install Fernschreiber on my Jolla Phone with Sailfish OS 3.4.0.24 installed.
Is this a known problem and is there a solution to resolve this?
I can only send but not receive messages with the 0.9 version. It would be good to be able to install the latest version.
Thanks ;)

**Comment by Wunderfitz** [comment]
Yes, it's a known problem - Jolla made an update to the OpenSSL library on newer versions which made older SFOS releases incompatible with the newest app releases. 

There is a Fernschreiber release dedicated to the Jolla Phone and other devices that haven't received SFOS4: https://openrepos.net/content/werkwolfoldschool/fernschreiber-jolla-phone-and-older-sfos-versions-only
