### ISSUE TITLE
Allow to see the exact timestamps for the chat messages

### ISSUE THREAD

**Issue by monich** [Wunderfitz/harbour-fernschreiber#47]
Relative timestamps are probably OK for the chat list but absolute timestamp is absolutely a must for the chat window. For example, I have a message sent "35 months" ago. That not only doesn't tell me what was the time when I sent it, one can't even say what day it was, even with the calculator. That's ridiculous.

If there are enough people who don't want to know when exactly the messages were sent, that sort of behavior could be made configurable. Maybe it could be toggled on touch like it's done in Jolla's Messages app (with last choice remembered), I'm not 100% sure. But something must be done about it.

**Comment by Wunderfitz** [comment]
Yep, a configurable or a 'tap to change' option is certainly a good idea. Not top prio, but yes, I see the problem.
