### ISSUE TITLE
No sound notification since upgrade to SailfishOS 4.4.0

### ISSUE THREAD

**Issue by the-real-ed** [Wunderfitz/harbour-fernschreiber#486]
Thanks for your work on this software.

Since upgrading to SailfishOS 4.4.0.58, I no longer get sound notifications from Fernschreiber on new messages. The phone will vibrate, and the notification lightly will turn blue (good), but there's no notification sound.

Other users have noted the issue on the [OpenRepos page](https://openrepos.net/content/werkwolf/fernschreiber).

Information:
SailfishOS version: 4.4.0.58
Fernschreiber: 0.13
Hardware: XA2 (H3113) (other users reported issues with Xperia X Compact).

Thanks

**Comment by Wunderfitz** [comment]
Seems that Jolla removed some default notification categories in Lipstick which Fernschreiber is using. The change seems to enable sounds again...

**Comment by the-real-ed** [comment]
Thanks, I just installed and tested 0.14 and it appears that the issue persists (no notification sound).

Let me know if there's additional information I can provide.

**Comment by Wunderfitz** [comment]
Follow up: https://forum.sailfishos.org/t/requesting-full-documentation-for-notification-options-x-nemo/11304

**Comment by Wunderfitz** [comment]
According to reports this is finally fixed with 0.15. Change 32a55c48be9eef64a66eb183fa3293b5ef453d7b was missing.

**Comment by olgabaranov** [comment]
I am having the same issue with Sailfish 4.6, Fernschreiber 0.17 on Xperia 10 lll. I get all notifications at once when I open the Fernschreiber, not as they come in.
