### ISSUE TITLE
Some links and handles in messages don't work

### ISSUE THREAD

**Issue by ApostolosB** [Wunderfitz/harbour-fernschreiber#491]
When a link (t.me/+jkshfkjsdhgkds) or handle (@whatever) is in a message it doesn't do anything in fern. Some give a wrong message ID warning. 
The same links in the web client either open a popup that prompts you to join a group or cancel, or request to join and in the case of handles they open a chat.

**Comment by Wunderfitz** [comment]
Yes, so far I couldn't find the correct handler in TDLib for such URLs, maybe I'm just missing something. Until this is really fixed, I open the regular URL handler for such links, see 81cf5b6852a2bc759b25a64dc9c002c941615912

**Comment by ApostolosB** [comment]
In many cases you tap on the link and it doesn't do anything so you are left wondering what happened. Anyway.

**Comment by Wunderfitz** [comment]
I guess I found a workaorund at least for the t.me/+... links with 0e7ae00a67900e6fea3f0f38f3532a1af1e2cb9d. However, some examples would be nice... ;)

**Comment by Wunderfitz** [comment]
Fixed with 0.16.

**Comment by ApostolosB** [comment]
I think it doesn't cover one more type of link. t.me/joinchat/_whatever_

**Comment by ApostolosB** [comment]
and i also see T.me/whatever not working. Might be affected by the capital first letter.
