### ISSUE TITLE
Can't send attached picture

### ISSUE THREAD

**Issue by almindor** [Wunderfitz/harbour-fernschreiber#498]
Shows "can't get file stat info" when trying to send attached pictures. The pictures show up in the selector ok. They were taken with the camera set to save to SD card.

Xperia X, sailfish OS 4.4.0.58 with fernscheirber 0.15

**Comment by Wunderfitz** [comment]
Already fixed with 4445be3302216266d8cbc49954e0d997e78b5e0f but we can keep this open until the next official release is there

**Comment by Wunderfitz** [comment]
Closing as 0.16 is now both in Jolla Store and on OpenRepos.
