### ISSUE TITLE
Copy to clipboard doesn't work in landscape

### ISSUE THREAD

**Issue by mbarashkov** [Wunderfitz/harbour-fernschreiber#549]
Copy to clipboard does nothing if you select it from the additional landscape mode menu (from the More Options... panel).

**Comment by Wunderfitz** [comment]
Currently can't reproduce it. On my tablet, the option is always in the first menu... Any hints how to reproduce it?

**Comment by mbarashkov** [comment]
This is always reproduced on my own messages. Copy is only the 5th option.
You can move it to the extended menu manually and see for yourself that it's broken (see the pull request).

**Comment by jgibbon** [comment]
Fix confirmed, thanks again!
