### ISSUE TITLE
Twemoji update to Unicode 15.0

### ISSUE THREAD

**Issue by jgibbon** [Wunderfitz/harbour-fernschreiber#561]
As we are aware, Twemoji became a bit out of date with the downfall of Twitter.

Community member dumol suggested using openmoji as an icon replacement: https://openmoji.org/library/

Steps to take:

1. Design/Taste check: Is openmojis design "nice enough" in general/are there any show-stoppers (contrast/background)? @Wunderfitz 
2. If 1. is OK: Adaptation of our qml integration @jgibbon 

An evaluation of Determinants c++ emoji parser (also twemoji) would be nice, but I guess we won't have time for that in the near future. https://github.com/R1tschY/harbour-determinant/blob/63204c9769084a5bf3342a74e5ea4d039c3938df/src/emojiparser.cpp

cheers

**Comment by dumol** [comment]
Just found out a fork of Twemoji is still alive and kicking: https://github.com/jdecked/twemoji.

**Comment by jgibbon** [comment]
Thanks @dumol, that should simplify things a bit!

Our parser most likely will still have to be adapted, but the rest should be straight forward…

cheers

**Comment by jgibbon** [comment]
Haha, please ignore that first commit, was using the wrong sytem…

Hopefully will be able to test this over the weekend and create a PR.

**Comment by jgibbon** [comment]
Status:
Updated emoji search db works (>200 new emojis or variants iirc).

The monochrome font used in sfos does not support all of them, so they won't be really useful within the textarea while typing the message. I don't think we'll try to override that.

**Comment by jgibbon** [comment]
Status:
Published the db creation script I threw together at https://github.com/jgibbon/fernie-emojidb
