### ISSUE TITLE
Notification - Pinned Messages

### ISSUE THREAD

**Issue by Mottel1** [Wunderfitz/harbour-fernschreiber#57]
Hi,

thank you so much for Fernschreiber1

I encountered the issue that when I muted chats I get a notification that the pinned message was updated anyways. Also in the notification and in the chat it is written: "Unsupported message: PinMessage". 

It is kind of annoying. How can I disable that? I do not find any option in the pully menu. 

Is this a bug?

**Comment by Wunderfitz** [comment]
If somebody pins a message, there is a notification - no matter which mute/unute settings you chose. That also applies to standard clients. But maybe you can make it configurable somewhen.

Concerning the "unsupported message": That's simply not implemented yet - like many other things. We've just begun and the release number 0.2 is there for a reason. ;)
