### ISSUE TITLE
Option to join and leave groups

### ISSUE THREAD

**Issue by Bsoupe** [Wunderfitz/harbour-fernschreiber#65]
It should be possible to join and leave groups.

**Comment by GNUuser** [comment]
@Wunderfitz this feature is not already implemented in next version?

**Comment by Wunderfitz** [comment]
At least leaving groups is already done - made by @jgibbon - joining groups is definitely top priority to be implemented.

**Comment by Wunderfitz** [comment]
Now finally implemented in v0.4
