### ISSUE TITLE
Multiple attachments (images) per chat message

### ISSUE THREAD

**Issue by andywuest** [Wunderfitz/harbour-fernschreiber#66]
It would be nice if it were possible to add multiple attachments (images) per chat message - if API provides that feature.

**Comment by Wunderfitz** [comment]
Unfortunately, this is not supported by the API, see https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1send_message.html and https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1input_message_photo.html
