### ISSUE TITLE
Downloading an image the second time fails

### ISSUE THREAD

**Issue by andywuest** [Wunderfitz/harbour-fernschreiber#67]
Hi, 

when i download an image from a chat message the second time - i get the onscreen message that the download failed - most likely the download did not really fail, but writing the file failed, because it already exists in the target directory. in this case it would be nice to have a more clear error message, which tells me that the downloaded file already exists, or something like that.

**Comment by Wunderfitz** [comment]
Thanks for reporting it, will be fixed with v0.3.
