### ISSUE TITLE
A quoted message disappears while typing a reply if the keyboard hide gesture is executed

### ISSUE THREAD

**Issue by lal883** [Wunderfitz/harbour-fernschreiber#69]
If a message is quoted by long pressing a message bubble and selecting "reply to message", and later while typing if the gesture to hide keyboard (swipe down on keyboard) is executed, the quoted message disappears.

**Comment by Wunderfitz** [comment]
That's actually intended - as soon as the focus is somewhere else, the in-reply-to information is discarded. Maybe I change that in the future or make it more transparent...

**Comment by lal883** [comment]
When I reply to a quoted message and changes orientation from portrait to landsace, the text entry region shifts to the top of the screen hiding the quoted message. That made me swipe down the keyboard to display the whole thing but deleting the quoted message. Initially thought changing orientation was dropping the quoted text, but later figured its my swipe down gesture that deletes it.

**Comment by Wunderfitz** [comment]
Fix should be in v0.3 :) Thanks for reporting that!
