### ISSUE TITLE
[feature request] option to mark chats as read or unread

### ISSUE THREAD

**Issue by lal883** [Wunderfitz/harbour-fernschreiber#70]
Would be nice to have a feature to mark all the new messages in an unread conversation as "read".

**Comment by Wunderfitz** [comment]
Mark as "unread" is not supported by Telegram (as far as I know). Mark as read was implemented in v0.4 by @jgibbon.

**Comment by yusssufff** [comment]
Hi!
Well both in the android app or on the Sailfish's "Depecher" app, each chat can be ticked as either "read" or "unread"...
