### ISSUE TITLE
Add optional "pure online mode" that doesn't use chat database on the phone

### ISSUE THREAD

**Issue by EarthlingX** [Wunderfitz/harbour-fernschreiber#77]
Thank you very much for your great efforts! :+1:

Currently Fernschreiber is using a local database on the phone for storage of messages, chat info etc. Unfortunately usage of databases leads to the requirement to always download and synchronize the database when starting the app.

In former competitor "Depecher" it was possible to disable any storage of database files (neither file database nor chat database or message database). Thanks to this option, starting the app is extremely fast because it will only download the current message list from the server without synchronizing chat histories. I would call this as some kind of "pure online mode" with avoidance of offline message storage.

Would it be possible to add such a feature to Fernschreiber?

**Comment by Wunderfitz** [comment]
Let's see - should be possible as that is configurable during initialization...
