### ISSUE TITLE
Icon sticker looks a little big compared with the rest.

### ISSUE THREAD

**Issue by GNUuser** [Wunderfitz/harbour-fernschreiber#86]
Also the current icon sticker is not color matching with the rest of icons. Original SAILFISH  sticker icon has a gray color background, so we need improve this icon with: exact size and exact color.

**Comment by GNUuser** [comment]
I am working to help with all graphics issues in Sailfish ecosystems, but I still  unable to help at the moment because i need reconfigure my personal computer.

**Comment by Wunderfitz** [comment]
Well, it's a custom sticker as I wasn't aware that there is a standard icon. Please indicate the ID of the standard sticker and I'll replace it.

**Comment by jgibbon** [comment]
I think he means icon-m-other (as depecher is using).

**Comment by GNUuser** [comment]
Yes Depecher is using the original-sailfish-sticker-icon.

**Comment by jgibbon** [comment]
Well, the sailfish icon not exactly meant for stickers as such, it just fits more or less.

Just for fun (and even funnier: invisible on white background here so you'll have to find the link between the dots), I made a mashup of both icons… perhaps everyone can agree on that one?
.........................
![icon-m-sticker](https://user-images.githubusercontent.com/99138/96501858-48ebdc80-1251-11eb-9e6a-7b8cc08ffcc9.png)
........................

**Comment by GNUuser** [comment]
Looking good! @jgibbon.

**Comment by Wunderfitz** [comment]
Yep, also looks better in the app:

![image](https://user-images.githubusercontent.com/15228698/96639805-840a1080-1322-11eb-8afd-0a08fdbf6101.png)

**Comment by Wunderfitz** [comment]
Thanks for the hint, @GNUuser and for the new icon @jgibbon!

**Comment by GNUuser** [comment]
Beautiful. When new release? :  )

**Comment by GNUuser** [comment]
@jgibbon do you resize the icon?  i just want the perfect size with Sailfish icons. ??

**Comment by jgibbon** [comment]
I didn't – but there are indeed possible scaling issues with just putting one prebuilt image there. The icons in `Theme` have different dimensions for different screen densities.
To be sure, one could force the width/height to `Theme.iconSizeMedium` (which IconButton doesn't do by default IIRC).

Also, those different icons simply have different amounts of white space: Visually, sticker, video and image are wider; while sticker and document are higher.

**Comment by GNUuser** [comment]
Yeah I checked all Sailfish icons core, seems there are  different dimensions. So the high with  sticker and document icon is same, so ok.  I think my poor vision comes from the sticker icon next to the documents icon then the documents icon is less wider. : ) 
Also I checked that there is not sticker icon in Sailfish core. So good work @Wunderfitz @jgibbon.
READY TO GO...

**Comment by GNUuser** [comment]
HI devs, What license is the  new sticker-smile?

**Comment by jgibbon** [comment]
My contributions are licensed the same as the rest of the application, which is GPL3.

**Comment by GNUuser** [comment]
Thank you. Depecher want to use it...

**Comment by jgibbon** [comment]
Depecher doesn't have a clear License defined as far as I can see, so in theory that could be problematic.
But as I don't care at all, I hereby grant Blacky or anyone usage under the Terms of the WTFPL including relicensing to whatever he/she/them likes.
Quick heads up: There likely will be an svg version of it at some point – that might be a better one to use. If I end up being the creator of that, the license grant will be valid for that, as well. 
Follow #102 to be up to date.
