### ISSUE TITLE
add search function

### ISSUE THREAD

**Issue by Bsoupe** [Wunderfitz/harbour-fernschreiber#9]
currently (V.0.1) there's no search option like in the original Telegram client. Please add!

**Comment by ferlanero** [comment]
An option to search in main page between tons os chats is absolutely necessary. Maybe this option could be a good solution as the name of the program (Fernschreiber) takes a lot of space in main page and is completely useless:
![Captura_20201208_001](https://user-images.githubusercontent.com/1192395/101489664-8c192080-3961-11eb-8264-72dc55df1370.png)

**Comment by vaskas** [comment]
Agree, also the "online" indicator in the top bar looks unimportant. What you really want to know is if you are offline for some reason.
